name: AbilitySlots
version: '${projectVersion}'
main: ru.ckateptb.abilityslots.AbilitySlots
api-version: 1.17
depend: [ Tablecloth, CommandAPI ]
softdepend: [ WorldGuard, GriefPrevention, Towny, LWC, LuckPerms]
loadbefore:
  - WorldGuard
authors: [ CKATEPTb ]
description: Ability manager. Craft and use passive, combo, and slot-based abilities.
permissions:
  abilityslots.*:
    default: op
    description: Gives the player full access to the plugin functionality
  abilityslots.energybar.display:
    default: true
    description: Players with this permission will see the ability energy display in the bossbar
  abilityslots.board.display:
    default: true
    description: Players with this permission will see the ability board on the scoreboard.
  abilityslots.abilities.categoryname:
    default: false
    description: Replace categoryname with the name of an existing category. Players with this permission can use abilities of this category.
  abilityslots.abilities.categoryname.abilityname:
    default: false
    description: Replace categoryname with the name of an existing category. Replace abilityname with the name of an existing ability. Players with this permission can use current ability.
#  abilityslots.command:
#    default: true
#    description: Allows the user to use the abilityslots command to get help.
#  abilityslots.command.bind:
#    default: true
#    description: Allows the user to use the abilityslots bind command to bind abilities to slots.
#  abilityslots.command.bind.other:
#    default: op
#    description: Allows the user to use the abilityslots bind command relative to other users.
#  abilityslots.command.clear:
#    default: true
#    description: Allows the user to use the abilityslots clear command to clear slots from abilities.
#  abilityslots.command.clear.other:
#    default: op
#    description: Allows the user to use the abilityslots clear command relative to other users.
#  abilityslots.command.reload:
#    default: op
#    description: Reload plugin.
